### ISSUE TITLE
Fix Project Folder Permissions

### ISSUE THREAD

**Issue by ericdowell** [ericdowell/laravel-circleci#1]
There is an issue with the current configured users/group that run `php-fpm` (`www-data`) and/or `nginx` (`nginx`) or maybe even just the `supervisor` configured user. I'm not sure yet.

This issue results in the following when testing with Laravel Dusk:
![failure-tests_browser_logintest__testloginuser-0](https://user-images.githubusercontent.com/525506/38786676-02d334c2-40ef-11e8-8b25-d6cb6edb5339.png)

I found some discussion on [serverfault](https://serverfault.com/questions/433265/how-do-i-change-the-nginx-user#answer-433266) about where these users and groups can be changed. 

A simple nuclear solution would be to set everything in `/home/circleci` to be `770` using `sudo chmod -R 770 /home/circleci`. I'm not too fond of this nuclear solution though.

## Current Solution (Per Project)
To fix this permissions issue the following can be added as a step to `.circleci/config.yml`:
```yml
version: 2
jobs:
  build:
    docker:
      - image: ericdowell/laravel-circleci:latest
    steps:

      - run:
          name: Fix app folder permissions
          command: sudo chmod -R 0777 storage/ && sudo chmod -R 0775 bootstrap/cache/ && sudo chmod 0775 public/robots.txt
```
